### PR TITLE
imports isomorphic-fetch in actions.js

### PR DESCRIPTION
**Pull request by jbenjaminy**

### CODE REVIEW

**Comment by Rosuav** [comment]
Wouldn't that require a package.json dependency?

Also, don't all modern browsers support this natively?

**Comment by jbenjaminy** [comment]
For some reason I thought I saw it in package.json, but I wasn't aware about the native support. Good to know!

**Comment by Rosuav** [comment]
The polyfill is there to support stupidly old browsers like IE, but everything decently modern supports fetch() out of the box. You're free to add it if you like, but I won't put it in the template.

**Comment by Rosuav** [comment]
Thanks for the PR though :)

**Comment by jbenjaminy** [comment]
No worries, just thought maybe it was overlooked. Shouldn't known better :))

**Pull request closed without merging**
